# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cell coordinates to data.frame (c++)
#'
#' C++ function that converts the cell coordinates of a matrix to a data.frame.
#' @param mat [matrix(numeric)][matrix]\cr object of which the cell coordinates
#'   are converted to a data.frame.
#' @return a data.frame of the cell coordinates
#' @export
cellToPointsCpp <- function(mat) {
    .Call(`_geomio_cellToPointsCpp`, mat)
}

#' Count cell adjacencies in a matrix (c++)
#'
#' C++ function that counts the number of unique values in a matrix
#' @param mat [matrix(numeric)][matrix]\cr the object in which to count
#'   adjacencies
#' @param doublecount [logical(1)][logical]\cr whether or not to tally up each
#'   adjacency for both neighbouring cells, or only once.
#' @family count functions
#' @return A data.frame of values*values with their adjacencies
#' @export
countCellAdjacenciesCpp <- function(mat, doublecount) {
    .Call(`_geomio_countCellAdjacenciesCpp`, mat, doublecount)
}

#' Count cell edges in a matrix (c++)
#'
#' C++ function that counts the number of edges in a matrix
#' @param mat [matrix(numeric)][matrix]\cr the object in which to count edges
#' @family count functions
#' @return A data.frame of the unique values and their edges
#' @export
countCellEdgesCpp <- function(mat) {
    .Call(`_geomio_countCellEdgesCpp`, mat)
}

#' Count unique cell values in a matrix (c++)
#'
#' C++ function that counts the number of unique values in a matrix
#' @param mat [matrix(numeric)][matrix]\cr the object in which to count unique
#'   values
#' @family count functions
#' @return A data.frame of the unique values and their number
#' @export
countCellValuesCpp <- function(mat) {
    .Call(`_geomio_countCellValuesCpp`, mat)
}

#' Generate a height map (c++)
#'
#' C++ function that generates a height map based on the diamond-square
#' algorithm
#' @param mat [matrix(numeric)][matrix]\cr the template matrix into which
#'   height values are written.
#' @param stepSize [numeric(.)][numeric]\cr ...
#' @param roughness [numeric(1)][numeric]\cr the Hurst exponent (fBm) or its
#'   equivalent, the roughness factor (DSa). Bounded between 0 and 1.
#' @param startDev [numeric(1)][numeric]\cr ...
#' @family matrix modify functions
#' @return A numeric matrix of the same dimensions as \code{mat} into which the
#'   values of a height map have been written.
#' @export
diamondSquareCpp <- function(mat, stepSize, roughness, startDev) {
    .Call(`_geomio_diamondSquareCpp`, mat, stepSize, roughness, startDev)
}

#' Get Matrix cell values (c++)
#'
#' C++ function that extracts the values of a matrix
#' @param mat [matrix(numeric)][matrix]\cr the matrix from which to extract the values.
#' @family extractor functions
#' @return numeric vector of the values in \code{mat}
#' @export
getValuesCpp <- function(mat) {
    .Call(`_geomio_getValuesCpp`, mat)
}

#' Calculate a distance map (c++)
#'
#' C++ function that derives a distance map of foreground patches in a matrix.
#' @param mat [matrix(numeric)][matrix]\cr the matrix with foreground patches
#'   from which to derive the distance map.
#' @param method [character(1)][character]\cr which of the methods
#'   \code{"euclidean"}, \code{"manhattan"} or \code{"chessboard"} to use.
#' @family matrix modify functions
#' @export
matDistanceCpp <- function(mat, method) {
    .Call(`_geomio_matDistanceCpp`, mat, method)
}

#' Cell (matrix) in polygon algorithm (c++)
#'
#' C++ function that determine whether the cells in a matrix are inside or
#' outside of a polygon.
#' @param mat [matrix(numeric)][matrix]\cr object of which the cell coordinates
#'   are tested against \code{geom}.
#' @param geom [matrix(numeric)][matrix]\cr matrix of the coordinates
#'   describing the polygon, where the first column represents x coordinate
#'   values and the second column y coordinate values.
#' @param negative [logical(1)][logical]\cr whether or not to test points are
#'   outside of a polygon.
#' @details Copyright 2000 softSurfer, 2012 Dan Sunday This code may be freely
#'   used and modified for any purpose providing that this copyright notice is
#'   included with it. SoftSurfer makes no warranty for this code, and cannot
#'   be held liable for any real or imagined damage resulting from its use.
#'   Users of this code must verify correctness for their application.
#' @family topological relationships
#' @return a numeric matrix
#' @export
matInGeomCpp <- function(mat, geom, negative) {
    .Call(`_geomio_matInGeomCpp`, mat, geom, negative)
}

#' "Reduce" a list of matrices (c++)
#'
#' C++ function that uses a binary function that successively combines a list
#' of matrices.
#' @param lMat [list(matrix)][list]\cr list of matrices with equal dimensions.
#' @param f [function(1)][function]\cr binary function to combine the matrices.
#' @family matrix modify functions
#' @return a single matrix of the same dimensions as all the input matrices.
#' @export
matReduceCpp <- function(lMat, f) {
    .Call(`_geomio_matReduceCpp`, lMat, f)
}

#' Scale values in a matrix (c++)
#'
#' C++ function that scales the values in a matrix between a provided range
#' @param mat [matrix(numeric)][matrix]\cr object in which the values are
#'   scaled.
#' @param range [numeric(2)][numeric]\cr two values (minimum and maximum)
#'   between which the values in \code{mat} shall be scaled.
#' @family matrix modify functions
NULL

scaleMatrixCpp <- function(mat, range) {
    .Call(`_geomio_scaleMatrixCpp`, mat, range)
}

#' Point in polygon algorithm (c++)
#'
#' C++ function that determine whether points are inside, outside or on the
#' boundary of a polygon.
#' @param vert [matrix(numeric)][matrix]\cr matrix of the coordinates
#'   describing the points, where the first column represents x coordinate
#'   values and the second column y coordinate values.
#' @param geom [matrix(numeric)][matrix]\cr matrix of the coordinates
#'   describing the polygon, where the first column represents x coordinate
#'   values and the second column y coordinate values.
#' @param invert [logical(1)][logical]\cr whether or not to test instead for
#'   points that are outside of the polygon.
#' @details This is an extension of the below described algorithm. It extends
#'   the "point in polygon" algorithm, which gives values 0 and 1 for points
#'   that are outside or inside of a polygon, respectively, by the values 2 and
#'   3, for points that are on one or two lines (a vertex) of the polygon,
#'   respectively (which is obviously a stark simplification that depends on
#'   the precision of floating-point values, but can be useful in some edge
#'   cases).
#'
#'   http://www.geomalgorithms.com/ Copyright 2000 softSurfer, 2012 Dan Sunday
#'   This code may be freely used and modified for any purpose providing that
#'   this copyright notice is included with it. SoftSurfer makes no warranty
#'   for this code, and cannot be held liable for any real or imagined damage
#'   resulting from its use. Users of this code must verify correctness for
#'   their application.
#' @family topological relationships
#' @return an integer vector of the same length as there are points in
#'   \code{vert} that indicates where the respective point is located.
#' @export
pointInPolyCpp <- function(vert, geom, invert) {
    .Call(`_geomio_pointInPolyCpp`, vert, geom, invert)
}

#' Extract and sort unique elements (c++)
#'
#' C++ function that extract and returns a sorted vector of numeric values.
#' @param x [numeric(.)][numeric]\cr the vector of numeric values
#' @family extractor functions
#' @return a numeric vector of the unique and sorted values.
#' @export
sortUniqueCpp <- function(x) {
    .Call(`_geomio_sortUniqueCpp`, x)
}

#' Replace character values with integer values (c++)
#'
#' C++ function that replaces character values with integer values in a matrix.
#' @param mat [matrix(character)][matrix]\cr the object in which to replaces
#'   character values.
#' @param replace [character(.)][character]\cr values to replace.
#' @param with [integerish(.)][integer]\cr values that replace the old values
#'   (must have same length as \code{replace}).
#' @return an integer matrix where values in \code{replace} have been replaced
#'   with values in \code{with}.
#' @family substitute functions
#' @export
subChrIntCpp <- function(mat, replace, with) {
    .Call(`_geomio_subChrIntCpp`, mat, replace, with)
}

#' Replace numeric values with character values (c++)
#'
#' C++ function that replaces numeric values with character values in a matrix.
#' @param mat [matrix(numeric)][matrix]\cr the object in which to replaces
#'   numeric values.
#' @param replace [numeric(.)][numeric]\cr values to replace.
#' @param with [character(.)][character]\cr values that replace the old values
#'   (must have same length as \code{replace}).
#' @return an character matrix where values in \code{replace} have been
#'   replaced with values in \code{with}.
#' @family substitute functions
#' @export
subNumChrCpp <- function(mat, replace, with) {
    .Call(`_geomio_subNumChrCpp`, mat, replace, with)
}

#' Replace numeric values with other numeric values (c++)
#'
#' C++ function that replaces numeric values with other numeric values in a
#' matrix.
#' @param mat [matrix(numeric)][matrix]\cr the object in which to replaces
#'   numeric values.
#' @param replace [numeric(.)][numeric]\cr values to replace.
#' @param with [character(.)][character]\cr values that replace the old values
#'   (must have same length as \code{replace}).
#' @return a numeric matrix where values in \code{replace} have been replaced
#'   with values in \code{with}.
#' @family substitute functions
#' @export
subNumNumCpp <- function(mat, replace, with) {
    .Call(`_geomio_subNumNumCpp`, mat, replace, with)
}

